name: Main
on:
  workflow_dispatch: {}

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
    - run: |
        git config --global http.https://github.com/gramLabs/.extraheader \
            "AUTHORIZATION: basic $(echo -n "x-access-token:${{ secrets.PAT }}}" | base64 -w 0)"
        go env -w "GOPRIVATE=github.com/gramLabs/*"
        go mod tidy
        go run .
        
        
