name: Main
on:
  workflow_dispatch: {}

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - user: actions/checkout@v3
    - uses: actions/setup-go@v4
    - run: |
        go mod tidy
        go run .
        
        
