name: Main
on:
  workflow_dispatch: {}

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
    - run: |
        cat ~/.netrc
        
        go env -w "GOPRIVATE=github.com/gramLabs/*"
        go mod tidy
        go run .
        
        
